=== edgecommons/edgecommons/resources/ggcommons-config-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GGCommons component configuration",
  "type": "object",
  "properties": {
    "logging": {
      "type": "object",
      "properties": {
        "level": { "type": "string" },
        "format": { "type": "string" },
        "fileLogging": {
          "type": "object",
          "properties": {
            "enabled": { "type": "boolean" },
            "filePath": { "type": "string" }
          },
          "additionalProperties": true
        },
        "loggers": { "type": "object" },
        "globalControl": { "type": "boolean" }
      },
      "additionalProperties": true
    },
    "metricEmission": {
      "type": "object",
      "properties": {
        "target": {
          "type": "string",
          "enum": ["log", "messaging", "cloudwatch", "cloudwatchcomponent"]
        },
        "namespace": { "type": "string" },
        "largeFleetWorkaround": { "type": "boolean" },
        "targetConfig": { "type": "object" }
      },
      "additionalProperties": true
    },
    "heartbeat": {
      "type": "object",
      "properties": {
        "intervalSecs": { "type": "integer", "minimum": 1 },
        "measures": {
          "type": "object",
          "properties": {
            "cpu": { "type": "boolean" },
            "memory": { "type": "boolean" },
            "disk": { "type": "boolean" },
            "threads": { "type": "boolean" },
            "files": { "type": "boolean" },
            "fds": { "type": "boolean" }
          },
          "additionalProperties": true
        },
        "targets": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": { "type": "string" },
              "config": { "type": "object" }
            },
            "required": ["type"],
            "additionalProperties": true
          }
        }
      },
      "additionalProperties": true
    },
    "tags": { "type": "object" },
    "component": {
      "type": "object",
      "properties": {
        "global": {},
        "instances": { "type": "array" }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": true
}

=== edgecommons/edgecommons/config_sample_with_logging.json
{
  "logging": {
    "level": "INFO",
    "format": "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n",
    "globalControl": true,
    "fileLogging": {
      "enabled": true,
      "filePath": "/var/log/{ComponentName}-{ThingName}.log"
    },
    "loggers": {
      "com.aws.proserve.ggcommons": "DEBUG",
      "com.aws.proserve.ggcommons.messaging": "TRACE",
      "org.apache.http": "WARN"
    }
  },
  "tags": {
    "Environment": "Development",
    "Application": "GGCommons",
    "Region": "us-west-2"
  },
  "heartbeat": {
    "intervalSecs": 60,
    "targets": [
      {
        "type": "metric"
      },
      {
        "type": "messaging",
        "config": {
          "destination": "iot_core",
          "topic": "heartbeat/{ThingName}/{ComponentName}"
        }
      }
    ]
  },
  "metricEmission": {
    "target": "cloudwatch",
    "namespace": "GGCommons/{Environment}",
    "dimensions": {
      "ThingName": "{ThingName}",
      "ComponentName": "{ComponentName}",
      "Application": "{Application}",
      "Region": "{Region}"
    }
  },
  "component": {
    "global": {
      "setting1": "value1",
      "setting2": "value2"
    },
    "instances": [
      {
        "id": "instance1",
        "config": {
          "param1": "instance1-value1",
          "param2": "instance1-value2"
        }
      },
      {
        "id": "instance2",
        "config": {
          "param1": "instance2-value1",
          "param2": "instance2-value2"
        }
      }
    ]
  }
}

=== edgecommons/edgecommons/libs/java/config_3.json
{
  "logging": {
    "level": "TRACE",
    "java_format": "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5p] %C{1} (%L) [%t] : %m%n"
  },
  "heartbeat": {
    "intervalSecs": 10,
    "measures": {
      "cpu": true,
      "memory": true,
      "disk": false,
      "files": true,
      "threads": true,
      "fds": true
    },
    "targets": [
      {
        "type": "metric"
      }
    ]
  },
  "tags": {
    "appId": "IntelliJIdea",
    "site": "site1",
    "shop": "shop1",
    "line": "line1"
  },
  "metricEmission": {
    "target": "messaging",
    "targetConfig": {
      "topic": "metrics/{ThingName}/data",
      "destination": "ipc"
    }
  },
  "component": {
    "global": {
    },
    "instances": [
      {
        "id": "kep1-right",
        "connectionInfo": {
          "url": "opc.tcp://DESKTOP-A3J778C:49320/",
          "security": {
            "type": "Anonymous",
            "ssl": {
              "client_cert": "",
              "client_key": "",
              "server_cert": ""
            }
          }
        },
        "defaultPublishInterval": 1000,
        "defaultSamplingRate": 500,
        "defaultQueueSize": 100,
        "metricsPublishInterval": 5,
        "writeRequestTopic": "{ThingName}/{ComponentName}/{InstanceId}/write",
        "readRequestTopic": "{ThingName}/{ComponentName}/{InstanceId}/read",
        "subscriptions": [
          {
            "id": "Sine Tags 1-3, 16 bit K Reg DWORDS",
            "publishInterval": 100,
            "include": [
              {
                "ns": 2,
                "tagExpression": "^Simulation Examples\\.Functions\\.Sine.*",
                "samplingRate": 50,
                "queueSize": 100,
                "pubTopic": "{ThingName}/{ComponentName}/{InstanceId}/sineTags"
              },
              {
                "ns": 2,
                "tagExpression": "^Data Type Examples\\.16 Bit Device\\.K Registers\\.DWord\\d",
                "samplingRate": 50,
                "queueSize": 100,
                "pubTopic": "{ThingName}/{ComponentName}/{InstanceId}/16bitKregs"
              }
            ],
            "exclude": [
              {
                "ns": 2,
                "tagExpression": "Simulation Examples\\.Functions\\.Sine4"
              }
            ]
          },
          {
            "id": "Tag1",
            "publishInterval": 100,
            "include": [
              {
                "ns": 2,
                "tagExpression": "^Channel1\\.Device1\\.Tag2",
                "samplingRate": 25,
                "queueSize": 100,
                "deadband": {
                  "type": "Absolute",
                  "value": 5
                },
                "pubTopic": "{ThingName}/{ComponentName}/{InstanceId}/ch1dev1Tag2"
              }
            ]
          }
        ]
      },
      {
        "id": "simulator-baremetal",
        "connectionInfo": {
          "url": "opc.tcp://OFFICE-3950X:53530/OPCUA/SimulationServer",
          "security": {
            "type": "Anonymous",
            "ssl": {
              "client_cert": "",
              "client_key": "",
              "server_cert": ""
            }
          }
        },
        "defaultPublishInterval": 1000,
        "defaultSamplingRate": 500,
        "defaultQueueSize": 100,
        "ipcPublishInterval": 0,
        "subscriptions": [
          {
            "id": "All",
            "publishInterval": 300,
            "include": [
              {
                "ns": 3,
                "tagExpression": "Sawtooth",
                "samplingRate": 100,
                "queueSize": 100,
                "deadband": {
                  "type": "None",
                  "value": 0.8
                },
                "pubTopic": "{ThingName}/{ComponentName}/{InstanceId}/all-tags"
              }
            ]
          }
        ]
      }
    ]
  }
}

=== edgecommons/edgecommons/libs/python/config_3.json
{
  "logging": {
    "level": "INFO",
    "python_format": "%(asctime)s [%(levelname)s] %(filename)s %(funcName)s(%(lineno)d) [%(threadName)s]: %(message)s"
  },
  "heartbeat": {
    "intervalSecs": 1,
    "targets": [
      {
        "type": "messaging",
        "config": {
          "destination": "ipc",
          "topic": "{ThingName}/{ComponentName}/heartbeat"
        }
      }
    ],
    "measures": {
      "cpu": true,
      "memory": true,
      "disk": false,
      "files": true,
      "threads": true,
      "fds": false
    }
  },
  "metricEmission": {
	"target" : "log",
    "namespace": "ggcommons",
    "largeFleetWorkaround": true,
	"targetConfig" : {
      "logFileName": "../{ComponentFullName}.metric.log"
    }
  },
  "tags": {
    "appId": "IntelliJIdea",
    "site": "site1",
    "shop": "shop1",
    "line": "line1"
  },
  "component": {
    "global": {
    },
    "instances": [
      {
        "id": "kep1-right",
        "connectionInfo": {
          "url": "opc.tcp://DESKTOP-A3J778C:49320/",
          "security": {
            "type": "Anonymous",
            "ssl": {
              "client_cert": "",
              "client_key": "",
              "server_cert": ""
            }
          }
        },
        "defaultPublishInterval": 1000,
        "defaultSamplingRate": 500,
        "defaultQueueSize": 100,
        "metricsPublishInterval": 5,
        "writeRequestTopic": "{ThingName}/{ComponentName}/{InstanceId}/write",
        "readRequestTopic": "{ThingName}/{ComponentName}/{InstanceId}/read",
        "subscriptions": [
          {
            "id": "Sine Tags 1-3, 16 bit K Reg DWORDS",
            "publishInterval": 100,
            "include": [
              {
                "ns": 2,
                "tagExpression": "^Simulation Examples\\.Functions\\.Sine.*",
                "samplingRate": 50,
                "queueSize": 100,
                "pubTopic": "{ThingName}/{ComponentName}/{InstanceId}/sineTags"
              },
              {
                "ns": 2,
                "tagExpression": "^Data Type Examples\\.16 Bit Device\\.K Registers\\.DWord\\d",
                "samplingRate": 50,
                "queueSize": 100,
                "pubTopic": "{ThingName}/{ComponentName}/{InstanceId}/16bitKregs"
              }
            ],
            "exclude": [
              {
                "ns": 2,
                "tagExpression": "Simulation Examples\\.Functions\\.Sine4"
              }
            ]
          },
          {
            "id": "Tag1",
            "publishInterval": 100,
            "include": [
              {
                "ns": 2,
                "tagExpression": "^Channel1\\.Device1\\.Tag2",
                "samplingRate": 25,
                "queueSize": 100,
                "deadband": {
                  "type": "Absolute",
                  "value": 5
                },
                "pubTopic": "{ThingName}/{ComponentName}/{InstanceId}/ch1dev1Tag2"
              }
            ]
          }
        ]
      },
      {
        "id": "simulator-baremetal",
        "connectionInfo": {
          "url": "opc.tcp://OFFICE-3950X:53530/OPCUA/SimulationServer",
          "security": {
            "type": "Anonymous",
            "ssl": {
              "client_cert": "",
              "client_key": "",
              "server_cert": ""
            }
          }
        },
        "defaultPublishInterval": 1000,
        "defaultSamplingRate": 500,
        "defaultQueueSize": 100,
        "ipcPublishInterval": 0,
        "subscriptions": [
          {
            "id": "All",
            "publishInterval": 300,
            "include": [
              {
                "ns": 3,
                "tagExpression": "Sawtooth",
                "samplingRate": 100,
                "queueSize": 100,
                "deadband": {
                  "type": "None",
                  "value": 0.8
                },
                "pubTopic": "{ThingName}/{ComponentName}/{InstanceId}/all-tags"
              }
            ]
          }
        ]
      }
    ]
  }
}

=== edgecommons/edgecommons/libs/rust/test-configs/config.json
{
  "logging": { "level": "DEBUG" },
  "heartbeat": {
    "enabled": true,
    "intervalSecs": 5,
    "measures": { "cpu": true, "memory": true },
    "destination": "local"
  },
  "metricEmission": { "target": "log", "namespace": "demo" },
  "tags": { "site": "factory-1" },
  "component": {
    "global": { "publish_interval": 3 },
    "instances": [ { "id": "main" }, { "id": "second" } ]
  }
}

=== edgecommons/edgecommons/templates/python/test-configs/config_1.json
{
  "logging": {
    "level": "INFO",
    "python_format": "%(asctime)s [%(levelname)s] %(filename)s %(funcName)s(%(lineno)d) [%(threadName)s]: %(message)s"
  },
  "heartbeat": {
    "enabled": true,
    "intervalSecs": 1,
    "measures": {
      "cpu": true,
      "memory": true,
      "disk": false,
      "files": true,
      "threads": true,
      "fds": false
    },
    "destination": "local"
  },
  "metricEmission": {
    "target": "log",
    "namespace": "ggcommons",
    "targetConfig": {
      "logFileName": "{ComponentFullName}.metric.log"
    }
  },
  "tags": {
    "appId": "IntelliJIdea",
    "site": "site1",
    "shop": "shop1",
    "line": "line1"
  },
  "component": {
    "global": {
      "publish_interval": 2
    },
    "instances": []
  }
}

=== edgecommons/edgecommons/libs/python/tests/test-config.json
{
  "logging": {
    "level": "DEBUG",
    "python_format": "%(asctime)s [%(levelname)s] %(name)s %(lineno)d: %(message)s"
  },
  "heartbeat": {
    "enabled": true,
    "intervalSecs": 2,
    "measures": {
      "cpu": true,
      "memory": true,
      "disk": false
    },
    "destination": "local"
  },
  "metricEmission": {
    "target": "messaging",
    "namespace": "TestApplication"
  },
  "tags": {
    "environment": "test",
    "site": "local"
  },
  "component": {
    "global": {
      "serverUrl": "https://api.test.com",
      "timeout": 5000
    },
    "instances": [
      {
        "id": "test",
        "database": {
          "host": "localhost",
          "port": 5432
        }
      }
    ]
  }
}

=== edgecommons/edgecommons/test-configs/JavaComponentSkeleton.json
{
  "logging": {
    "level": "INFO",
    "format": "%d{yyyy-MM-dd HH:mm:ss} [%-5p] %-25.25c{1}(%4L): %m%n"
  },
  "heartbeat": {
    "topic": "heartbeat/{ThingName}/{ComponentName}",
    "intervalSecs": 5,
    "metric": {
      "cpu": true,
      "memory": true,
      "disk": false
    }
  },
  "tags": {
    "appId": "ABC12345",
    "site": "site1",
    "shop": "shop1",
    "line": "line1"
  },
  "component": {
    "global": {
      "publish_interval": 3,
      "message": "Hello World config_1!"
    },
    "instances": [
      {
        "id":  "first",
        "param1": "dummy1"
      },
      {
        "id": "second",
        "param1": "dummy2"
      }
    ]
  }
}

=== edgecommons/edgecommons/libs/java/config_sample_with_logging.json
{
  "logging": {
    "level": "INFO",
    "java_format": "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n",
    "globalControl": true,
    "fileLogging": {
      "enabled": true,
      "filePath": "/var/log/{ComponentName}-{ThingName}.log"
    },
    "loggers": {
      "com.mbreissi.edgecommons": "DEBUG",
      "com.mbreissi.edgecommons.messaging": "TRACE",
      "org.apache.http": "WARN"
    }
  },
  "tags": {
    "Environment": "Development",
    "Application": "EdgeCommons",
    "Region": "us-west-2"
  },
  "heartbeat": {
    "intervalSecs": 60,
    "destination": "iotcore"
  },
  "metricEmission": {
    "target": "cloudwatch",
    "namespace": "EdgeCommons/{Environment}",
    "dimensions": {
      "ThingName": "{ThingName}",
      "ComponentName": "{ComponentName}",
      "Application": "{Application}",
      "Region": "{Region}"
    }
  },
  "component": {
    "global": {
      "setting1": "value1",
      "setting2": "value2"
    },
    "instances": [
      {
        "id": "instance1",
        "config": {
          "param1": "instance1-value1",
          "param2": "instance1-value2"
        }
      },
      {
        "id": "instance2",
        "config": {
          "param1": "instance2-value1",
          "param2": "instance2-value2"
        }
      }
    ]
  }
}
